[book]
title = "牛逼笔记"
authors = ["ermaolaoye"]
language = "en,zh-CN"
multilingual = true
src = "src"

[preprocessor.katex]
after = ["links"]

[preprocessor.emojicodes]

[preprocessor.pagetoc]
[output.html]
additional-css = [
    "theme/pagetoc.css",
    "theme/css/speaker-notes.css",
    "theme/css/image.css"
]
additional-js  = ["theme/pagetoc.js"]

[output.html.fold]
enable = true

