[book]
title = "牛逼笔记"
authors = ["ermaolaoye"]
language = "en,zh-CN"
multilingual = true
src = "src"

[preprocessor.katex]
after = ["links"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
